### ISSUE TITLE
Please Bump ZeroTier Unraid Docker 

### ISSUE THREAD

**Issue by tomtom215** [Spikhalskiy/docker-templates#7]
Hi there,

Would you mind bumping your zerotier docker to the latest version? 
https://github.com/zerotier/ZeroTierOne/blob/dev/RELEASE-NOTES.md

I also noticed your Unraid support URL is dead (which is why I'm opening an issue here) 
https://unraid.net/forums/topic/72030-support-spikhalskiy-zerotier

Thanks for the help!

**Comment by Spikhalskiy** [comment]
Zerotier was upgraded to 1.12.0, the link to support forum was updated.
